-- MySQL Script generated by MySQL Workbench
-- Fri Aug 30 12:32:48 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema blackboard
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blackboard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blackboard` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `blackboard` ;

-- -----------------------------------------------------
-- Table `blackboard`.`announcements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blackboard`.`announcements` ;

CREATE TABLE IF NOT EXISTS `blackboard`.`announcements` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `lecture_id` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(255) NOT NULL,
  `maintext` TEXT NOT NULL,
  `regdate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idx`),
  INDEX `lecture_idx` (`lecture_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blackboard`.`lectures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blackboard`.`lectures` ;

CREATE TABLE IF NOT EXISTS `blackboard`.`lectures` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `lecture_id` VARCHAR(255) NOT NULL,
  `lecture_name` VARCHAR(255) NOT NULL,
  `professor_id` VARCHAR(255) NULL DEFAULT NULL,
  `max_num` INT NOT NULL,
  `cur_num` INT NOT NULL,
  PRIMARY KEY (`idx`),
  UNIQUE INDEX `lecture_id` (`lecture_id` ASC) VISIBLE,
  INDEX `professor_id` (`professor_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blackboard`.`members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blackboard`.`members` ;

CREATE TABLE IF NOT EXISTS `blackboard`.`members` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `studentnum` VARCHAR(255) NULL DEFAULT NULL,
  `identity` ENUM('student', 'teacher') NOT NULL,
  PRIMARY KEY (`idx`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blackboard`.`student_lecture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blackboard`.`student_lecture` ;

CREATE TABLE IF NOT EXISTS `blackboard`.`student_lecture` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `student_id` VARCHAR(255) NULL DEFAULT NULL,
  `lecture_id` VARCHAR(255) NULL DEFAULT NULL,
  `lecture_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idx`),
  INDEX `student_lecture_ibfk_1` (`student_id` ASC) VISIBLE,
  INDEX `student_lecture_ibfk_2` (`lecture_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
